version: "3.9"
services:
  postmyrustache:
    image: postmyrustache/postmyrustache:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=1234
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
